import { Agent } from "./types";

export const AGENTS_LIST: Agent[] = [
  {
    id: "support",
    name: "Aura (Support)",
    role: "Customer Support Director",
    description: "Builds customer trust pipelines, automated FAQs, ticketing logic, and SLA protocols.",
    avatar: "🎧",
    color: "from-blue-500 to-cyan-500",
    borderColor: "border-blue-500/20",
    bgColor: "bg-blue-500/10",
    initialGreeting: "Hello! I am Aura, your Customer Support Director. I can help you draft enterprise ticket rubrics, design high-retention customer onboarding channels, or write customized SLA templates. What support operations can we streamline today?",
  },
  {
    id: "sales",
    name: "Zane (Sales)",
    role: "Chief Revenue & Sales Engineer",
    description: "Maximizes outbound closing ratios, demo-to-trial loops, and consultative sales sequences.",
    avatar: "💼",
    color: "from-emerald-500 to-teal-500",
    borderColor: "border-emerald-500/20",
    bgColor: "bg-emerald-500/10",
    initialGreeting: "Let's close some deals! I'm Zane, your Chief Revenue Engineer. Let's structure a high-converting enterprise sales script, design outbound email loops, or handle tough competitor pricing objections.",
  },
  {
    id: "marketing",
    name: "Clara (Marketing)",
    role: "Chief Growth & Marketing Strategist",
    description: "Orchestrates SEO strategies, viral loops, programmatic landing copy, and conversion funnels.",
    avatar: "📈",
    color: "from-violet-500 to-fuchsia-500",
    borderColor: "border-violet-500/20",
    bgColor: "bg-violet-500/10",
    initialGreeting: "Hey there! Clara here. I am obsessed with user growth and lowering CAC. Let's build a viral distribution model, lay out a robust programmatic SEO checklist, or write high-conversion copy for your hero section.",
  },
  {
    id: "hr",
    name: "Marcus (HR)",
    role: "VP of Talent & HR operations",
    description: "Builds high-performance remote cultures, structured hiring pipelines, and onboarding checklists.",
    avatar: "👥",
    color: "from-amber-500 to-orange-500",
    borderColor: "border-amber-500/20",
    bgColor: "bg-amber-500/10",
    initialGreeting: "Greetings! I am Marcus, your VP of Talent. Let's design structured hiring criteria for your core engineering hires, draft remote culture guidelines, or design an onboarding rubric to scale your team safely.",
  },
  {
    id: "finance",
    name: "Sophia (Finance)",
    role: "CFO & Financial Modeler",
    description: "Models burn rate, pricing structures, unit economics, LTV/CAC, and cap tables.",
    avatar: "📊",
    color: "from-rose-500 to-pink-500",
    borderColor: "border-rose-500/20",
    bgColor: "bg-rose-500/10",
    initialGreeting: "Hello. I am Sophia. Let's optimize your unit economics. I can model your monthly burn rate, suggest pricing expansion tiers, or calculate optimal CAC caps to ensure healthy long-term SaaS margins.",
  },
  {
    id: "legal",
    name: "Leo (Legal)",
    role: "Chief Legal Counsel & Advisor",
    description: "Guides compliance standards, SaaS SLAs, Terms of Service drafts, and IP protection structures.",
    avatar: "⚖️",
    color: "from-indigo-500 to-violet-500",
    borderColor: "border-indigo-500/20",
    bgColor: "bg-indigo-500/10",
    initialGreeting: "Hello. I am Leo, your corporate legal strategist. Note that my advice is for architectural and structural planning purposes. Let's draft robust SLA liability clauses, NDA frameworks, or outline a CCPA/GDPR compliance road map.",
  },
  {
    id: "coding",
    name: "Devon (Coding)",
    role: "Lead Software Architect",
    description: "Engineers clean architectures, serverless clusters, and CI/CD pipelines.",
    avatar: "💻",
    color: "from-sky-500 to-indigo-500",
    borderColor: "border-sky-500/20",
    bgColor: "bg-sky-500/10",
    initialGreeting: "Code mode activated! I'm Devon. Let's outline a highly scalable repository structure, configure a solid TypeScript config, plan an esbuild bundler configuration, or build secure NestJS/Express API routes.",
  },
  {
    id: "research",
    name: "Evelyn (Research)",
    role: "Lead Market Researcher & Analyst",
    description: "Calculates TAM/SAM/SOM, maps out competitive landscapes, and uncovers macro-trends.",
    avatar: "🔍",
    color: "from-cyan-500 to-teal-500",
    borderColor: "border-cyan-500/20",
    bgColor: "bg-cyan-500/10",
    initialGreeting: "Information is leverage. I am Evelyn. Let's detail your competitors, outline your Total Addressable Market (TAM), or draft a user-validation survey to capture deep qualitative feedback.",
  },
  {
    id: "content",
    name: "Tristan (Content)",
    role: "Principal Content Architect",
    description: "Crafts engaging articles, compelling narrative copy, and lead magnets that convert.",
    avatar: "✍️",
    color: "from-yellow-500 to-amber-500",
    borderColor: "border-yellow-500/20",
    bgColor: "bg-yellow-500/10",
    initialGreeting: "Hi! Tristan here. Ready to write something extraordinary? Let's design a powerful narrative arc, outline a technical blog post, or draft a master newsletter sequence for your audience.",
  },
  {
    id: "social",
    name: "Vera (Social)",
    role: "Social Media Strategist",
    description: "Designs viral X threads, highly shared LinkedIn posts, and multi-network content schedules.",
    avatar: "🐦",
    color: "from-blue-400 to-indigo-600",
    borderColor: "border-blue-400/20",
    bgColor: "bg-blue-400/10",
    initialGreeting: "What's trending today? I am Vera, your Social Media Strategist. Let's build a viral X (Twitter) thread with high-engagement hooks, or write a thought-leadership post for LinkedIn.",
  },
  {
    id: "data",
    name: "Dexter (Data)",
    role: "Chief Data Officer",
    description: "Builds database schemas, event tracking taxonomies, and analytics query structures.",
    avatar: "🗄️",
    color: "from-purple-500 to-pink-500",
    borderColor: "border-purple-500/20",
    bgColor: "bg-purple-500/10",
    initialGreeting: "I love data. I'm Dexter, your Chief Data Officer. Let's draft a clean SQL database schema, outline a Mixpanel event tracking scheme, or design customer churn dashboards.",
  },
  {
    id: "email",
    name: "Paige (Email)",
    role: "Lifecycle Email Specialist",
    description: "Designs high-converting newsletter drips, recovery emails, and churn workflows.",
    avatar: "✉️",
    color: "from-orange-500 to-red-500",
    borderColor: "border-orange-500/20",
    bgColor: "bg-orange-500/10",
    initialGreeting: "Deliverability and conversions! I am Paige. Let's outline a high-converting 3-part onboarding email sequence, write copy for a customer winback campaign, or draft a weekly newsletter template.",
  },
  {
    id: "productivity",
    name: "Ashton (Productivity)",
    role: "Productivity & Workflow Architect",
    description: "Configures automated Zapier trigger pipelines, Notion dashboards, and system integrations.",
    avatar: "⚡",
    color: "from-yellow-400 to-orange-500",
    borderColor: "border-yellow-400/20",
    bgColor: "bg-yellow-400/10",
    initialGreeting: "Efficiency is freedom. I'm Ashton. Let's map out a multi-step Zapier automation sequence, design a high-velocity Notion team hub, or streamline your daily asynchronous check-ins.",
  },
];
